# Generated by Django 2.2.14 on 2020-07-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rwat',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
