# Generated by Django 2.2.14 on 2020-07-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_homepage_user2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage", old_name="user2", new_name="tests",
        ),
    ]
