# Generated by Django 2.2.14 on 2020-07-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_homepage_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="tests",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
